name: codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest # 添加 ubuntu-latest 的运行系统
    
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
